### ISSUE TITLE
Week2 Alpha

### ISSUE THREAD

**Issue by jaytlennon** [QuantitativeBiodiversity/QB-2017#20]
@wrshoemaker and @klocey:

1) Thought re: Chao2. Seems like using singletons (n1) and doubletons (n2) fom site-by-species matrix of comparative data (collection of lakes) makes more sense then from say an experimental data set where n1 and n2 may be influenced by treatments. Perhaps in this case, only consider n1 and n2 from replicates within a treatment? Did some searching, but wasn't able to conceptually resolve. I don't think Handout needs to be changed to reflect, just thinking.... : )

2) On lines 167, we talk about sampling without replacement for rarefaction, but on line 169 language seems to suggest with replacement. Am I just confused?

3) On line 213, do we need `site1 <- site1[site1 >0]`? The `rac` function already seems to remove zero-abundance taxa. If not needed, delete for clarity. 

4) On line 380, I added text to clarify interpretation of residual sums of squares. Check for accuracy. 

5) On lines 311 and 334 we code out Shannon's and Simpsons using for loops. This is the first time in the course that we do this and it may be confusing to some students. Can we include some language, perhaps just for the first time (Shannon) where we explain in a more gentle walk-through way like on line 155 when we nicely introduce Chao2 formulation? Also, somewhat related, I remember two years ago we got some criticisms of the technicality of use of H; it's used to define function and as in return. I'm not savvy enough of a programmer to be aware of these sorts of things. 

6) Line 419, can we add lognromal equation like we did for Broken Stick and Preemption?

7) Line 431, what does the addition beta parameter do in the Mandelbrot compared to Zipf that makes it special mathematically and/or ecologically. Can we add a phrase to clarify?

**Comment by wrshoemaker** [comment]
1) Maybe we could use this as an opportunity to ask the students why it would not be appropriate to treat all of these sites the same.

2) I'm unsure what in line 169 of alpha_handout suggests sampling with replacement. I've clarified that the repeated samples are each without replacement in line 168.

3) `site1 <- site1[site1 >0]` is redundant and has been removed. 

4) - [x]  Looks good. I added some text for clarity on line 380.

5) Explanation of Shannon's H function added. That's a good point regarding the use of a variable for both the name of the returned item and the name of the function. From what I understand it's not considered good practice, even though we get the right result. I've changed that for both 
Shannon's and Simpson's.

6) - [x] Done. Equation taken from [the description of each RAC model in Vegan](https://cran.r-project.org/web/packages/vegan/vignettes/diversity-vegan.pdf)

7) Added a line to clarify the Beta parameter in the Zipf-Mandlebrot .
