### ISSUE TITLE
Appendix, Alpha Week2

### ISSUE THREAD

**Issue by jaytlennon** [QuantitativeBiodiversity/QB-2017#23]
Have been talking with @nwisnoski this week and there was the idea of attempting to streamline some of the handouts by creating an appendix at the end of the handout Rmd. Here we could put more detailed explanations, extra code, etc. Students might be more likely to reference this than opening up supplement file, which currently are not very curated.  

To this end, I moved some code from Week2 supplement to Week2 appendix. This included code for Ace and extra material for Evar. There's a term in Evar, however, (i.e. S) that is not defined. @klocey can you look at this? Either fix or delete? Thanks. cc: @wrshoemaker

**Comment by wrshoemaker** [comment]
Closed this issue, as it was fixed by @klocey 's recent changes to Week2.
